#188 Triggers events on the event handler for completed and expired q…
UQcsse3200/2023-studio-1 pull request #252
Opened 2023-09-11 13:44 UTC by lucashicks1

#Overview

PR to implement the firing of events to the `MissionManager` event handler when quests/achievements are completed/expired. This will enable the quests/achievements indicator (see #188 ) to not have to continuously poll the `MissionManager` service.

2023-09-11 21:21 UTC, lucashicks1 commented
Like when new quests are accepted or new quests become available?

2023-09-11 21:21 UTC, lucashicks1 commented
> Can we also add an event for new quests? 

See comment

2023-09-11 21:22 UTC, lucashicks1 commented
> Can we also add an event for new quests? 

Like when new quests are accepted or new quests become available?

2023-09-11 21:35 UTC, Tom-Strooper requested changes
We will have to make a few more changes to implement this properly, including updating our testing suites. We should probably have some way of triggering these events in the base classes.
Might I suggest that we move this over to sprint 3 with other updates to the mission system (i.e., making the mandatory quests)?

2023-09-15 04:48 UTC, Tom-Strooper approved these changes
I think the updates might make it easier for others to trigger the required events when they make missions. Pending approval from team 2 and other team members.

2023-09-16 06:18 UTC, merged