665 disable removing items for tools
UQcsse3200/2023-studio-1 pull request #679
Opened 2023-10-15 07:02 UTC by nimeshgarg

2023-10-15 08:42 UTC, JTrenerry commented on source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
> +    private final List<String> forbiddenItems = Arrays.asList("shovel","hoe","watering_can","scythe","sword","gun");
fishing rod :(

2023-10-15 08:43 UTC, JTrenerry requested changes
Left comments

2023-10-15 15:45 UTC, nimeshgarg commented on source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
> +    private final List<String> forbiddenItems = Arrays.asList("shovel","hoe","watering_can","scythe","sword","gun");
Added fishing rod

2023-10-15 15:47 UTC, nimeshgarg commented
> Left comments

Fixed

2023-10-16 00:12 UTC, tristanduncombe approved these changes
LGTM

2023-10-16 02:35 UTC, JTrenerry approved these changes

2023-10-16 03:44 UTC, merged